import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from 'react-hot-toast';
import NetworkProvider from '@/contexts/NetworkProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh`}
      >
        <NetworkProvider>
          <Toaster
            position='top-center'
            reverseOrder={false}
            gutter={8}
            containerClassName=''
            containerStyle={{}}
            toasterId='default'
            toastOptions={{
              // Define default options
              className: '',
              duration: 2000,

              style: {
                background: '#fff',
                color: '#202124',
              },

              // Default options for specific types
              success: {
                duration: 3000,
              },
            }}
          />
          <Navbar />
          <main className='flex items-center justify-center mt-10 max-w-5xl mx-auto'>
            {children}
          </main>
        </NetworkProvider>
      </body>
    </html>
  );
}
